name: Teleport Machine ID SSH
on:
  push:
    branches: [ main ]

jobs:
  execute-remote-command:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Crucial for GitHub OIDC
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Teleport Tooling
        uses: teleport-actions/setup@v1
        with:
          version: 14.3.3
          proxy: myteleport3.duckdns.org:3080

      - name: Fetch Short-lived Credentials
        uses: teleport-actions/auth@v1
        id: auth
        env:
          TELEPORT_INSECURE: "true"
          TELEPORT_PROXY: "myteleport3.duckdns.org:3080"
        with:
          proxy: myteleport3.duckdns.org:3080
          token: github-action-token

      - name: Execute Remote Uptime Check
  run: ssh -F ${{ steps.auth.outputs.ssh-config }} ubuntu@node-02.myteleport3.duckdns.org "uptime"

